CREATE DATABASE MAIN_DB;

CREATE TABLE CUSTOMER_HISTORY
(
	ACCOUNT VARCHAR (100) NOT NULL,
	TICKET VARCHAR(100) NOT NULL,
	TRANSACTIONS NVARCHAR(100) NOT NULL
);

CREATE TABLE ADMIIN
(
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) PRIMARY KEY NOT NULL ,
	CONTACT VARCHAR(100) NOT NULL,
	PASSWORD NVARCHAR(100) NOT NULL,
	PICTURE IMAGE 
);

DROP TABLE CUSTOMER_HISTORY;
DROP TABLE ADMIIN;